#######################################
# Docker stack for generating 
# certificates only
# by Julien BAYLE
#######################################

version: "2"

services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy
    tty: true
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./data/ssl:/etc/nginx/ssl
     - ./data/letsencrypt:/etc/letsencrypt
     - /etc/hosts:/etc/hosts
    links:
     - mailcatcher:fargo
     - mailcatcher:combo
     - mailcatcher:rabbitmq
     - mailcatcher:authentic
     - mailcatcher:wcs
     - mailcatcher:passerelle
     - mailcatcher:hobo
     - mailcatcher:pgadmin
     - mailcatcher:webmail
    environment:
     - ENV
     - DOMAIN
     - EMAIL

  mailcatcher:
    container_name: mailcatcher
    image: ascendhit/mailcatcher
